### PR TITLE
suppressed exclusive* when no min/max specified

### LINKED ISSUE #25: Suppress 'exclusive(Max|Min)imum' for unbounded range ends
JSON schema spec (the version used in OAS2) specifies that `exclusiveMinimum`/`exclusiveMaximum` should only be present when corresponding `maximum`/`minimum` ([spec link](https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.1.2)). SwaggerGen, however, emits `exclusive*` fields for unbounded range ends:
```
api Test
endpoint /positive-integer
method GET
response 200 int[1,>
```
results in 
```
"schema": {
  "type": "integer",
  "format": "int32",
  "minimum": 1,
  "exclusiveMaximum": true
}
```

### PR DESCRIPTION
**Pull request by weirdan**
Fixes #25 (for numeric types, anyway)

### CODE REVIEW

**Comment by weirdan** [comment]
Will need to adjust expectations in #23 when it's merged

**Comment by vanderlee** [comment]
Well spotted! Do you have any other pull requests coming in? If not, then I'll increase the version number so package managers will pick up the new fixes.

**Comment by weirdan** [comment]
No, that was the last of them for now

**Comment by weirdan** [comment]
>  Apparently there is still a bug in the unittests for one of the exclusive* tests

That's what I was talking about here:

> Will need to adjust expectations in #23 when it's merged

Since it's my unittest broken by my other PR I'm going to fix it in a few minutes.

**Pull request merged**
