### PR TITLE
additionalProperties support

### LINKED ISSUE #30: additionalProperties support
I'm going to propose PR for `additionalProperties` object type attribute, and wanted to check with you on the inline definition format I envision:
```
object(type)
object(propName:type,propName2:type,type)
object(type,propName:type,...,type) // errors out with 
                                    // 'duplicate additionalProperties type specified'
{[integer]} // string -> array of int hash
```
The command form would be:
```
additionalproperties type // a bit of a mouthful, 
                          // but close to the spec language on the other hand
```

### PR DESCRIPTION
**Pull request by weirdan**
fixes #30

### CODE REVIEW

**Comment by weirdan** [comment]
Hi @vanderlee, is there anything else I could do for this to get released?

**Comment by vanderlee** [comment]
I guess reminding me that this was still open would be a good start ;)
Completely forgot about it.
Since it seems fine, I'll merge it and bump the version number for packagist later today

**Comment by weirdan** [comment]
Yeah, it was, but there's no numbered release that includes this feature yet, so one has to use `dev-master` as one's package constraint in `composer.json`.

**Comment by vanderlee** [comment]
I probably just forgot to push the tag. Will do so later today

**Comment by vanderlee** [comment]
Done! Version is now 2.3.17

**Pull request merged**
